

#pragma once

#define CONNECTIONS_NUM_MAX 10240

#define IO_WORKER_COUNT 10
#define TASK_WORKER_COUNT_PER_IO_WORKER 20

#define EPOLL_FD_MAX ((CONNECTIONS_NUM_MAX / IO_WORKER_COUNT) + 1)
#define EPOLL_EVENT_MAX EPOLL_FD_MAX

#define SESSION_READ_BUFFER_SIZE 4096
#define SESSION_WRITE_BUFFER_SIZE 4096
